# Generated by Django 5.2.1 on 2025-05-12 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_teamranking_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamranking',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='planner.team'),
        ),
    ]
