# Generated by Django 5.2.1 on 2025-05-20 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='minute',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)]),
        ),
    ]
