# Generated by Django 5.2.1 on 2025-05-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_remove_round_name_league_owner_match_is_finished_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teamranking',
            constraint=models.UniqueConstraint(fields=('team', 'league'), name='unique_team_league'),
        ),
    ]
