# Generated by Django 5.2.1 on 2025-06-06 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_teamranking_unique_team_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatistics',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='planner.player'),
        ),
    ]
