# Generated by Django 5.2.1 on 2025-06-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_alter_playerstatistics_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='player_profiles/'),
        ),
    ]
