# Generated by Django 5.2.1 on 2025-06-08 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_alter_league_owner_alter_match_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.player'),
        ),
    ]
